In [1]:
import numpy as np
import matplotlib.pyplot as plt
import math

In [2]:
# force numpy array to print with decimal places
np.set_printoptions(formatter={'float': lambda x: "{0:0.17f}".format(x)})

In [3]:
# dimension of empty numpy array
m = 3
n = 10
Table_empty = np.zeros([m, n])
Table_empty

array([[0.00000000000000000, 0.00000000000000000, 0.00000000000000000,
        0.00000000000000000, 0.00000000000000000, 0.00000000000000000,
        0.00000000000000000, 0.00000000000000000, 0.00000000000000000,
        0.00000000000000000],
       [0.00000000000000000, 0.00000000000000000, 0.00000000000000000,
        0.00000000000000000, 0.00000000000000000, 0.00000000000000000,
        0.00000000000000000, 0.00000000000000000, 0.00000000000000000,
        0.00000000000000000],
       [0.00000000000000000, 0.00000000000000000, 0.00000000000000000,
        0.00000000000000000, 0.00000000000000000, 0.00000000000000000,
        0.00000000000000000, 0.00000000000000000, 0.00000000000000000,
        0.00000000000000000]])

In [5]:
# Roger's arm constant
arm1_mass = 0.2 #/* [kg] - mass of arm link 1 (upper arm) */
arm2_mass = 0.2 #/* [kg] - mass of arm link 2 (forearm)   */
arm_offset = 0.18 #/* [m] - 1/2 distance between arms */
length_arm1 = 0.5 #/* [m] - the length of link 1 */
length_arm2 = 0.5 #/* [m] - the length of link 2 */
arm1_inertia = arm1_mass * length_arm1 * length_arm1 #/* [kg m^2] - link 1 moment of inertia */
arm2_inertia = arm2_mass * length_arm2 * length_arm2 #/* [kg m^2] - link 2 moment of inertia */

print('arm1_inertia:{0:.8f}'.format(arm1_inertia),
     '\tarm2_inertia:{0:.8f}'.format(arm2_inertia))

arm1_inertia:0.05000000 	arm2_inertia:0.05000000


In [6]:
def get_natural_frequency(K, I=arm1_inertia):
    return math.sqrt(K/I)

In [7]:
K = 80.0

In [8]:
get_natural_frequency(K)

40.0

In [9]:
def get_damping_constant(W, I=arm1_inertia, Z=1.0):
    return 2 * Z * W * I

In [10]:
get_damping_constant(get_natural_frequency(K))

4.0

In [11]:
def get_Table(Table, K, inertia=arm1_inertia, step=0.0001):
    newK = K
    for i in range(0, n):
        Table[0][i] = newK
        Table[1][i] = get_natural_frequency(Table[0][i], inertia)
        Table[2][i] = get_damping_constant(Table[1][i], inertia, 1.0)
        newK += step
    return Table

In [16]:
K = 80
step = 5
T_arm1_f80_0 = get_Table(Table_empty, K, arm1_inertia, step)
T_arm1_f80_0

array([[80.00000000000000000, 85.00000000000000000, 90.00000000000000000,
        95.00000000000000000, 100.00000000000000000,
        105.00000000000000000, 110.00000000000000000,
        115.00000000000000000, 120.00000000000000000,
        125.00000000000000000],
       [40.00000000000000000, 41.23105625617660763, 42.42640687119285303,
        43.58898943540673798, 44.72135954999579610, 45.82575694955839651,
        46.90415759823429909, 47.95831523312719469, 48.98979485566356118,
        50.00000000000000000],
       [4.00000000000000000, 4.12310562561766059, 4.24264068711928566,
        4.35889894354067398, 4.47213595499957961, 4.58257569495583983,
        4.69041575982342973, 4.79583152331272000, 4.89897948556635665,
        5.00000000000000000]])

In [14]:
K = 40
step = 5
T_arm1_f1_0 = get_Table(Table_empty, K, arm1_inertia, step)
T_arm1_f1_0

array([[40.00000000000000000, 45.00000000000000000, 50.00000000000000000,
        55.00000000000000000, 60.00000000000000000, 65.00000000000000000,
        70.00000000000000000, 75.00000000000000000, 80.00000000000000000,
        85.00000000000000000],
       [28.28427124746190202, 30.00000000000000000, 31.62277660168379256,
        33.16624790355400165, 34.64101615137754919, 36.05551275463989214,
        37.41657386773941596, 38.72983346207416844, 40.00000000000000000,
        41.23105625617660763],
       [2.82842712474619029, 3.00000000000000000, 3.16227766016837952,
        3.31662479035540025, 3.46410161513775527, 3.60555127546398957,
        3.74165738677394177, 3.87298334620741702, 4.00000000000000000,
        4.12310562561766059]])

In [17]:
K = 180
step = 10
T_arm1_f1_0 = get_Table(Table_empty, K, arm1_inertia, step)
T_arm1_f1_0

array([[180.00000000000000000, 190.00000000000000000,
        200.00000000000000000, 210.00000000000000000,
        220.00000000000000000, 230.00000000000000000,
        240.00000000000000000, 250.00000000000000000,
        260.00000000000000000, 270.00000000000000000],
       [60.00000000000000000, 61.64414002968976547, 63.24555320336758513,
        64.80740698407859668, 66.33249580710800331, 67.82329983125268313,
        69.28203230275509839, 70.71067811865475505, 72.11102550927978427,
        73.48469228349534887],
       [6.00000000000000000, 6.16441400296897690, 6.32455532033675905,
        6.48074069840786038, 6.63324958071080051, 6.78232998312526902,
        6.92820323027551055, 7.07106781186547551, 7.21110255092797914,
        7.34846922834953542]])

In [18]:
K = 300
step = 10
T_arm1_f1_0 = get_Table(Table_empty, K, arm1_inertia, step)
T_arm1_f1_0

array([[300.00000000000000000, 310.00000000000000000,
        320.00000000000000000, 330.00000000000000000,
        340.00000000000000000, 350.00000000000000000,
        360.00000000000000000, 370.00000000000000000,
        380.00000000000000000, 390.00000000000000000],
       [77.45966692414833688, 78.74007874011810770, 80.00000000000000000,
        81.24038404635960831, 82.46211251235321527, 83.66600265340755982,
        84.85281374238570606, 86.02325267042627388, 87.17797887081347596,
        88.31760866327846315],
       [7.74596669241483404, 7.87400787401181113, 8.00000000000000000,
        8.12403840463596083, 8.24621125123532117, 8.36660026534075563,
        8.48528137423857132, 8.60232526704262845, 8.71779788708134795,
        8.83176086632784596]])

In [19]:
K = 100
step = 10
T_arm1_f1_0 = get_Table(Table_empty, K, arm1_inertia, step)
T_arm1_f1_0

array([[100.00000000000000000, 110.00000000000000000,
        120.00000000000000000, 130.00000000000000000,
        140.00000000000000000, 150.00000000000000000,
        160.00000000000000000, 170.00000000000000000,
        180.00000000000000000, 190.00000000000000000],
       [44.72135954999579610, 46.90415759823429909, 48.98979485566356118,
        50.99019513592784847, 52.91502622129181077, 54.77225575051661366,
        56.56854249492380404, 58.30951894845300387, 60.00000000000000000,
        61.64414002968976547],
       [4.47213595499957961, 4.69041575982342973, 4.89897948556635665,
        5.09901951359278538, 5.29150262212918143, 5.47722557505166208,
        5.65685424949238058, 5.83095189484530074, 6.00000000000000000,
        6.16441400296897690]])

In [23]:
K = 11
step = 1
T_arm1_f11_0 = get_Table(Table_empty, K, eye_inertia, step)
T_arm1_f11_0

array([[11.00000000000000000, 12.00000000000000000, 13.00000000000000000,
        14.00000000000000000, 15.00000000000000000, 16.00000000000000000,
        17.00000000000000000, 18.00000000000000000, 19.00000000000000000,
        20.00000000000000000],
       [370.80992435478316338, 387.29833462074168438,
        403.11288741492745658, 418.33001326703777067,
        433.01270189221929741, 447.21359549995793259,
        460.97722286464431818, 474.34164902525685648,
        487.33971724044818075, 499.99999999999994316],
       [0.05932958789676531, 0.06196773353931868, 0.06449806198638840,
        0.06693280212272605, 0.06928203230275509, 0.07155417527999328,
        0.07375635565834310, 0.07589466384404110, 0.07797435475847171,
        0.08000000000000000]])

In [24]:
K = 21
step = 1
T_arm1_f21_0 = get_Table(Table_empty, K, eye_inertia, step)
T_arm1_f21_0

array([[21.00000000000000000, 22.00000000000000000, 23.00000000000000000,
        24.00000000000000000, 25.00000000000000000, 26.00000000000000000,
        27.00000000000000000, 28.00000000000000000, 29.00000000000000000,
        30.00000000000000000],
       [512.34753829797989511, 524.40442408507578875,
        536.19026473818041723, 547.72255750516615080,
        559.01699437494744416, 570.08771254956900520,
        580.94750193111258341, 591.60797830996159519,
        602.07972893961471073, 612.37243569579447922],
       [0.08197560612767679, 0.08390470785361213, 0.08579044235810887,
        0.08763560920082659, 0.08944271909999160, 0.09121403400793104,
        0.09295160030897802, 0.09465727652959387, 0.09633275663033836,
        0.09797958971132713]])

In [ ]:
# 30 6.5 for inverse Kinematic