In [1]:
import numpy as np
import matplotlib.pyplot as plt
import math

In [2]:
# force numpy array to print with decimal places
np.set_printoptions(formatter={'float': lambda x: "{0:0.17f}".format(x)})

In [3]:
# dimension of empty numpy array
m = 3
n = 10
Table_empty = np.zeros([m, n])
Table_empty

array([[0.00000000000000000, 0.00000000000000000, 0.00000000000000000,
        0.00000000000000000, 0.00000000000000000, 0.00000000000000000,
        0.00000000000000000, 0.00000000000000000, 0.00000000000000000,
        0.00000000000000000],
       [0.00000000000000000, 0.00000000000000000, 0.00000000000000000,
        0.00000000000000000, 0.00000000000000000, 0.00000000000000000,
        0.00000000000000000, 0.00000000000000000, 0.00000000000000000,
        0.00000000000000000],
       [0.00000000000000000, 0.00000000000000000, 0.00000000000000000,
        0.00000000000000000, 0.00000000000000000, 0.00000000000000000,
        0.00000000000000000, 0.00000000000000000, 0.00000000000000000,
        0.00000000000000000]])

In [4]:
# Roger's eye constant
eye_mass = 0.05
eye_link = 0.04
eye_inertia = eye_mass * eye_link * eye_link
print('eye_mass:{0:.8f}'.format(eye_mass),
      '\teye_link:{0:.8f}'.format(eye_link),
      '\teye_intertia:{0:.8f}'.format(eye_inertia))

eye_mass:0.05000000 	eye_link:0.04000000 	eye_intertia:0.00008000


In [5]:
def get_natural_frequency(K, I=eye_inertia):
    return math.sqrt(K/I)

In [6]:
get_natural_frequency(1.0)

111.80339887498948

In [7]:
def get_damping_constant(W, I=eye_inertia, Z=1.0):
    return 2 * Z * W * I

In [8]:
get_damping_constant(get_natural_frequency(1.0))

0.01788854381999832

In [9]:
0.01788854381999832 / 0.00008

223.60679774997897

In [10]:
def get_Table(Table, K, inertia=eye_inertia, step=0.0001):
    newK = K
    for i in range(0, n):
        Table[0][i] = newK
        Table[1][i] = get_natural_frequency(Table[0][i], inertia)
        Table[2][i] = get_damping_constant(Table[1][i], inertia, 1.0)
        newK += step
    return Table

# Compute K and B

In [11]:
K = 0.1
step = 0.1
T_eye_f1_0 = get_Table(Table_empty, K, eye_inertia, step)
T_eye_f1_0

array([[0.10000000000000001, 0.20000000000000001, 0.30000000000000004,
        0.40000000000000002, 0.50000000000000000, 0.59999999999999998,
        0.69999999999999996, 0.79999999999999993, 0.89999999999999991,
        0.99999999999999989],
       [35.35533905932737753, 50.00000000000000000, 61.23724356957945503,
        70.71067811865475505, 79.05694150420947608, 86.60254037844386232,
        93.54143466934851858, 99.99999999999998579,
        106.06601717798211837, 111.80339887498948315],
       [0.00565685424949238, 0.00800000000000000, 0.00979795897113271,
        0.01131370849898476, 0.01264911064067352, 0.01385640646055102,
        0.01496662954709576, 0.01600000000000000, 0.01697056274847714,
        0.01788854381999832]])

In [12]:
K = 1
step = 0.1
T_eye_f1_0 = get_Table(Table_empty, K, eye_inertia, step)
T_eye_f1_0

array([[1.00000000000000000, 1.10000000000000009, 1.20000000000000018,
        1.30000000000000027, 1.40000000000000036, 1.50000000000000044,
        1.60000000000000053, 1.70000000000000062, 1.80000000000000071,
        1.90000000000000080],
       [111.80339887498948315, 117.26039399558574416,
        122.47448713915891005, 127.47548783981962117,
        132.28756555322954114, 136.93063937629153770,
        141.42135623730951011, 145.77379737113253100,
        150.00000000000002842, 154.11035007422444210],
       [0.01788854381999832, 0.01876166303929372, 0.01959591794226543,
        0.02039607805437114, 0.02116601048851673, 0.02190890230020665,
        0.02262741699796952, 0.02332380757938121, 0.02400000000000001,
        0.02465765601187591]])

In [13]:
K = 2
step = 0.1
T_eye_f1_0 = get_Table(Table_empty, K, eye_inertia, step)
T_eye_f1_0

array([[2.00000000000000000, 2.10000000000000009, 2.20000000000000018,
        2.30000000000000027, 2.40000000000000036, 2.50000000000000044,
        2.60000000000000053, 2.70000000000000062, 2.80000000000000071,
        2.90000000000000080],
       [158.11388300841895216, 162.01851746019650591,
        165.83123951777000116, 169.55824957813169362,
        173.20508075688775307, 176.77669529663688763,
        180.27756377319946068, 183.71173070873837219,
        187.08286933869709401, 190.39432764659773056],
       [0.02529822128134704, 0.02592296279363144, 0.02653299832284320,
        0.02712931993250107, 0.02771281292110204, 0.02828427124746190,
        0.02884441020371192, 0.02939387691339814, 0.02993325909419154,
        0.03046309242345564]])

In [14]:
K = 3
step = 1
T_eye_f1_0 = get_Table(Table_empty, K, eye_inertia, step)
T_eye_f1_0

array([[3.00000000000000000, 4.00000000000000000, 5.00000000000000000,
        6.00000000000000000, 7.00000000000000000, 8.00000000000000000,
        9.00000000000000000, 10.00000000000000000, 11.00000000000000000,
        12.00000000000000000],
       [193.64916731037084219, 223.60679774997896629,
        249.99999999999997158, 273.86127875258307540,
        295.80398915498079759, 316.22776601683790432,
        335.41019662496842102, 353.55339059327371842,
        370.80992435478316338, 387.29833462074168438],
       [0.03098386676965934, 0.03577708763999664, 0.04000000000000000,
        0.04381780460041330, 0.04732863826479693, 0.05059644256269407,
        0.05366563145999495, 0.05656854249492380, 0.05932958789676531,
        0.06196773353931868]])

In [15]:
K = 8
step = 0.5
T_eye_f1_0 = get_Table(Table_empty, K, eye_inertia, step)
T_eye_f1_0

array([[8.00000000000000000, 8.50000000000000000, 9.00000000000000000,
        9.50000000000000000, 10.00000000000000000, 10.50000000000000000,
        11.00000000000000000, 11.50000000000000000, 12.00000000000000000,
        12.50000000000000000],
       [316.22776601683790432, 325.96012026013244167,
        335.41019662496842102, 344.60121880225551649,
        353.55339059327371842, 362.28441865473598682,
        370.80992435478316338, 379.14377220257750878,
        387.29833462074168438, 395.28470752104743724],
       [0.05059644256269407, 0.05215361924162119, 0.05366563145999495,
        0.05513619500836089, 0.05656854249492380, 0.05796550698475776,
        0.05932958789676531, 0.06066300355241241, 0.06196773353931868,
        0.06324555320336760]])

In [16]:
K = 12
step = 1
T_eye_f1_0 = get_Table(Table_empty, K, eye_inertia, step)
T_eye_f1_0

array([[12.00000000000000000, 13.00000000000000000, 14.00000000000000000,
        15.00000000000000000, 16.00000000000000000, 17.00000000000000000,
        18.00000000000000000, 19.00000000000000000, 20.00000000000000000,
        21.00000000000000000],
       [387.29833462074168438, 403.11288741492745658,
        418.33001326703777067, 433.01270189221929741,
        447.21359549995793259, 460.97722286464431818,
        474.34164902525685648, 487.33971724044818075,
        499.99999999999994316, 512.34753829797989511],
       [0.06196773353931868, 0.06449806198638840, 0.06693280212272605,
        0.06928203230275509, 0.07155417527999328, 0.07375635565834310,
        0.07589466384404110, 0.07797435475847171, 0.08000000000000000,
        0.08197560612767679]])

In [17]:
K = 20
step = 1
T_eye_f1_0 = get_Table(Table_empty, K, eye_inertia, step)
T_eye_f1_0

array([[20.00000000000000000, 21.00000000000000000, 22.00000000000000000,
        23.00000000000000000, 24.00000000000000000, 25.00000000000000000,
        26.00000000000000000, 27.00000000000000000, 28.00000000000000000,
        29.00000000000000000],
       [499.99999999999994316, 512.34753829797989511,
        524.40442408507578875, 536.19026473818041723,
        547.72255750516615080, 559.01699437494744416,
        570.08771254956900520, 580.94750193111258341,
        591.60797830996159519, 602.07972893961471073],
       [0.08000000000000000, 0.08197560612767679, 0.08390470785361213,
        0.08579044235810887, 0.08763560920082659, 0.08944271909999160,
        0.09121403400793104, 0.09295160030897802, 0.09465727652959387,
        0.09633275663033836]])

In [18]:
K = 30
step = 1
T_eye_f1_0 = get_Table(Table_empty, K, eye_inertia, step)
T_eye_f1_0

array([[30.00000000000000000, 31.00000000000000000, 32.00000000000000000,
        33.00000000000000000, 34.00000000000000000, 35.00000000000000000,
        36.00000000000000000, 37.00000000000000000, 38.00000000000000000,
        39.00000000000000000],
       [612.37243569579447922, 622.49497989943654375,
        632.45553203367580863, 642.26162893325636105,
        651.92024052026488334, 661.43782776614762042,
        670.82039324993684204, 680.07352543677211543,
        689.20243760451103299, 698.21200218844705887],
       [0.09797958971132713, 0.09959919678390985, 0.10119288512538814,
        0.10276186062932102, 0.10430723848324239, 0.10583005244258363,
        0.10733126291998990, 0.10881176406988355, 0.11027239001672177,
        0.11171392035015154]])

In [15]:
K = 0.5
step = 0.1
T_eye_f05_0 = get_Table(Table_empty, K, eye_inertia, step)
T_eye_f05_0

array([[0.50000000000000000, 0.59999999999999998, 0.69999999999999996,
        0.79999999999999993, 0.89999999999999991, 0.99999999999999989,
        1.09999999999999987, 1.19999999999999996, 1.30000000000000004,
        1.40000000000000013],
       [79.05694150420947608, 86.60254037844386232, 93.54143466934851858,
        99.99999999999998579, 106.06601717798211837,
        111.80339887498948315, 117.26039399558572995,
        122.47448713915889584, 127.47548783981962117,
        132.28756555322954114],
       [0.01264911064067352, 0.01385640646055102, 0.01496662954709576,
        0.01600000000000000, 0.01697056274847714, 0.01788854381999832,
        0.01876166303929372, 0.01959591794226543, 0.02039607805437114,
        0.02116601048851673]])

In [75]:
T_eye_f01_0 = get_Table(Table_empty, 0.1, eye_inertia, 0.1)
T_eye_f01_0

array([[0.10000000000000001, 0.20000000000000001, 0.30000000000000004,
        0.40000000000000002, 0.50000000000000000, 0.59999999999999998,
        0.69999999999999996, 0.79999999999999993, 0.89999999999999991,
        0.99999999999999989],
       [35.35533905932737753, 50.00000000000000000, 61.23724356957945503,
        70.71067811865475505, 79.05694150420947608, 86.60254037844386232,
        93.54143466934851858, 99.99999999999998579,
        106.06601717798211837, 111.80339887498948315],
       [0.00565685424949238, 0.00800000000000000, 0.00979795897113271,
        0.01131370849898476, 0.01264911064067352, 0.01385640646055102,
        0.01496662954709576, 0.01600000000000000, 0.01697056274847714,
        0.01788854381999832]])

In [76]:
T_eye_f15_0 = get_Table(Table_empty, 1.5, eye_inertia, 0.1)
T_eye_f15_0

array([[1.50000000000000000, 1.60000000000000009, 1.70000000000000018,
        1.80000000000000027, 1.90000000000000036, 2.00000000000000044,
        2.10000000000000053, 2.20000000000000062, 2.30000000000000071,
        2.40000000000000080],
       [136.93063937629153770, 141.42135623730951011,
        145.77379737113250258, 150.00000000000000000,
        154.11035007422441367, 158.11388300841898058,
        162.01851746019650591, 165.83123951777000116,
        169.55824957813172205, 173.20508075688775307],
       [0.02190890230020665, 0.02262741699796952, 0.02332380757938120,
        0.02400000000000000, 0.02465765601187591, 0.02529822128134704,
        0.02592296279363144, 0.02653299832284320, 0.02712931993250108,
        0.02771281292110204]])

In [89]:
K = 1000
step = 0.1
T_eye_f1_0 = get_Table(Table_empty, K, eye_inertia, step)
T_eye_f1_0

array([[1000.00000000000000000, 1000.10000000000002274,
        1000.20000000000004547, 1000.30000000000006821,
        1000.40000000000009095, 1000.50000000000011369,
        1000.60000000000013642, 1000.70000000000015916,
        1000.80000000000018190, 1000.90000000000020464],
       [3535.53390593273752529, 3535.71067820883763488,
        3535.88744164742911380, 3536.06419624983618633,
        3536.24094201738444099, 3536.41767895139901157,
        3536.59440705320366760, 3536.77112632412263338,
        3536.94783676547922369, 3537.12453837859675332],
       [0.56568542494923801, 0.56571370851341407, 0.56574199066358866,
        0.56577027139997382, 0.56579855072278151, 0.56582682863222389,
        0.56585510512851267, 0.56588338021185969, 0.56591165388247677,
        0.56593992614057553]])

In [21]:
# Roger's arm constant
arm1_mass = 0.2 #/* [kg] - mass of arm link 1 (upper arm) */
arm2_mass = 0.2 #/* [kg] - mass of arm link 2 (forearm)   */
arm_offset = 0.18 #/* [m] - 1/2 distance between arms */
length_arm1 = 0.5 #/* [m] - the length of link 1 */
length_arm2 = 0.5 #/* [m] - the length of link 2 */
arm1_inertia = arm1_mass * length_arm1 * length_arm1 #/* [kg m^2] - link 1 moment of inertia */
arm2_inertia = arm2_mass * length_arm2 * length_arm2 #/* [kg m^2] - link 2 moment of inertia */

print('arm1_inertia:{0:.8f}'.format(arm1_inertia),
     '\tarm2_inertia:{0:.8f}'.format(arm2_inertia))

arm1_inertia:0.05000000 	arm2_inertia:0.05000000


In [22]:
T_arm1_f1_0 = get_Table(Table_empty, 1, arm1_inertia, 0.0001)
T_arm1_f1_0

array([[1.00000000, 1.00010000, 1.00020000, 1.00030000, 1.00040000,
        1.00050000, 1.00060000, 1.00070000, 1.00080000, 1.00090000],
       [4.47213595, 4.47235956, 4.47258315, 4.47280673, 4.47303029,
        4.47325385, 4.47347739, 4.47370093, 4.47392445, 4.47414796],
       [0.44721360, 0.44723596, 0.44725831, 0.44728067, 0.44730303,
        0.44732538, 0.44734774, 0.44737009, 0.44739245, 0.44741480]])

In [23]:
T_arm1_f10_0 = get_Table(Table_empty, 10, arm1_inertia, 10)
T_arm1_f10_0

array([[10.00000000, 20.00000000, 30.00000000, 40.00000000, 50.00000000,
        60.00000000, 70.00000000, 80.00000000, 90.00000000, 100.00000000],
       [14.14213562, 20.00000000, 24.49489743, 28.28427125, 31.62277660,
        34.64101615, 37.41657387, 40.00000000, 42.42640687, 44.72135955],
       [1.41421356, 2.00000000, 2.44948974, 2.82842712, 3.16227766,
        3.46410162, 3.74165739, 4.00000000, 4.24264069, 4.47213595]])

In [24]:
T_arm1_f80_0 = get_Table(Table_empty, 80, arm1_inertia, 10)
T_arm1_f80_0

array([[80.00000000, 90.00000000, 100.00000000, 110.00000000,
        120.00000000, 130.00000000, 140.00000000, 150.00000000,
        160.00000000, 170.00000000],
       [40.00000000, 42.42640687, 44.72135955, 46.90415760, 48.98979486,
        50.99019514, 52.91502622, 54.77225575, 56.56854249, 58.30951895],
       [4.00000000, 4.24264069, 4.47213595, 4.69041576, 4.89897949,
        5.09901951, 5.29150262, 5.47722558, 5.65685425, 5.83095189]])